-- Insert 12 avatars per race (72 total) with placeholder URLs
INSERT INTO avatars (race, image_url) VALUES
-- Eldorian avatars
('Eldorian', '/avatars/Eldorian/1.png'),
('Eldorian', '/avatars/Eldorian/2.png'),
('Eldorian', '/avatars/Eldorian/3.png'),
('Eldorian', '/avatars/Eldorian/4.png'),
('Eldorian', '/avatars/Eldorian/5.png'),
('Eldorian', '/avatars/Eldorian/6.png'),
('Eldorian', '/avatars/Eldorian/7.png'),
('Eldorian', '/avatars/Eldorian/8.png'),
('Eldorian', '/avatars/Eldorian/9.png'),
('Eldorian', '/avatars/Eldorian/10.png'),
('Eldorian', '/avatars/Eldorian/11.png'),
('Eldorian', '/avatars/Eldorian/12.png'),
-- Solarian avatars
('Solarian', '/avatars/Solarian/1.png'),
('Solarian', '/avatars/Solarian/2.png'),
('Solarian', '/avatars/Solarian/3.png'),
('Solarian', '/avatars/Solarian/4.png'),
('Solarian', '/avatars/Solarian/5.png'),
('Solarian', '/avatars/Solarian/6.png'),
('Solarian', '/avatars/Solarian/7.png'),
('Solarian', '/avatars/Solarian/8.png'),
('Solarian', '/avatars/Solarian/9.png'),
('Solarian', '/avatars/Solarian/10.png'),
('Solarian', '/avatars/Solarian/11.png'),
('Solarian', '/avatars/Solarian/12.png'),
-- Stoneborn avatars
('Stoneborn', '/avatars/Stoneborn/1.png'),
('Stoneborn', '/avatars/Stoneborn/2.png'),
('Stoneborn', '/avatars/Stoneborn/3.png'),
('Stoneborn', '/avatars/Stoneborn/4.png'),
('Stoneborn', '/avatars/Stoneborn/5.png'),
('Stoneborn', '/avatars/Stoneborn/6.png'),
('Stoneborn', '/avatars/Stoneborn/7.png'),
('Stoneborn', '/avatars/Stoneborn/8.png'),
('Stoneborn', '/avatars/Stoneborn/9.png'),
('Stoneborn', '/avatars/Stoneborn/10.png'),
('Stoneborn', '/avatars/Stoneborn/11.png'),
('Stoneborn', '/avatars/Stoneborn/12.png'),
-- Maritans avatars
('Maritans', '/avatars/Maritans/1.png'),
('Maritans', '/avatars/Maritans/2.png'),
('Maritans', '/avatars/Maritans/3.png'),
('Maritans', '/avatars/Maritans/4.png'),
('Maritans', '/avatars/Maritans/5.png'),
('Maritans', '/avatars/Maritans/6.png'),
('Maritans', '/avatars/Maritans/7.png'),
('Maritans', '/avatars/Maritans/8.png'),
('Maritans', '/avatars/Maritans/9.png'),
('Maritans', '/avatars/Maritans/10.png'),
('Maritans', '/avatars/Maritans/11.png'),
('Maritans', '/avatars/Maritans/12.png'),
-- Zephyrians avatars
('Zephyrians', '/avatars/Zephyrians/1.png'),
('Zephyrians', '/avatars/Zephyrians/2.png'),
('Zephyrians', '/avatars/Zephyrians/3.png'),
('Zephyrians', '/avatars/Zephyrians/4.png'),
('Zephyrians', '/avatars/Zephyrians/5.png'),
('Zephyrians', '/avatars/Zephyrians/6.png'),
('Zephyrians', '/avatars/Zephyrians/7.png'),
('Zephyrians', '/avatars/Zephyrians/8.png'),
('Zephyrians', '/avatars/Zephyrians/9.png'),
('Zephyrians', '/avatars/Zephyrians/10.png'),
('Zephyrians', '/avatars/Zephyrians/11.png'),
('Zephyrians', '/avatars/Zephyrians/12.png'),
-- Vortani avatars
('Vortani', '/avatars/Vortani/1.png'),
('Vortani', '/avatars/Vortani/2.png'),
('Vortani', '/avatars/Vortani/3.png'),
('Vortani', '/avatars/Vortani/4.png'),
('Vortani', '/avatars/Vortani/5.png'),
('Vortani', '/avatars/Vortani/6.png'),
('Vortani', '/avatars/Vortani/7.png'),
('Vortani', '/avatars/Vortani/8.png'),
('Vortani', '/avatars/Vortani/9.png'),
('Vortani', '/avatars/Vortani/10.png'),
('Vortani', '/avatars/Vortani/11.png'),
('Vortani', '/avatars/Vortani/12.png');